# -*- coding: utf-8 -*-
"""ML_Zinniarethie Andari K.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HQghUBgbTrqL-ecijuo5OT_cM875VixB

# From Data to Insight: Exploratory Data Analysis

## Pengertian Analisis Data
Analisis data adalah proses mengolah data untuk menghasilkan informasi yang berguna dalam pengambilan keputusan berbasis data.

## Perbedaan Descriptive Analysis dan EDA
Descriptive analysis menjelaskan apa yang terjadi pada data, sedangkan EDA bertujuan menemukan pola, tren, dan hubungan antar variabel.

## Pentingnya Data Cleaning
Data cleaning diperlukan untuk memastikan data bebas dari kesalahan, duplikasi, dan inkonsistensi sehingga hasil analisis lebih akurat.

## Peran Visualisasi Data
Visualisasi membantu menyampaikan insight data secara jelas dan mudah dipahami oleh pengambil keputusan.

# Proyek Analisis Data: Bike Sharing Dataset
- **Nama:** [Zinniarethie Andari K]

## Menentukan Pertanyaan Bisnis

- Apakah bisa kita melihat seberapa sering sepeda dipakai?
- Bagaimana hubungan cuaca dengan sebearapa sering sepeda dipakai?

### Import Semua Packages/Library yang Digunakan
"""

# @title Import Library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
df = pd.read_csv('day.csv')
df.head()

"""## Data Wrangling

### Gathering Data
"""

from google.colab import files
uploaded = files.upload()

# @title Load Data set
df = pd.read_csv('day.csv')
df.head()

"""**Insight:**
- Uploud data
- Menampilkan 5 data teratas

### Assessing Data
"""

df.info()

df.isnull().sum()

df.duplicated().sum()

df.describe()

df['season'].unique()
df['weathersit'].unique()

"""**Insight:**
- Info
- Mencari tahu data duplikat
- Mencari data unik

### Cleaning Data
"""

# @title Seleksi dan Pembersihan Kolom
df = df.drop(columns=[
    'instant',      # ID data
    'dteday',       # tanggal (tidak dipakai langsung)
    'casual',       # bagian dari cnt
    'registered'    # bagian dari cnt
])

# @title Tampilan data setelah diseleksi
df.head()

# @title Preprocessing & Labeling
df['cnt_class'] = pd.qcut(
    df['cnt'],
    q=3,
    labels=['rendah', 'sedang', 'tinggi']
)

df = df.drop(columns=['cnt'])
df.head()

"""## Exploratory Data Analysis (EDA) & Visualization"""

# @title Distribusi Kelas Target
class_counts = df['cnt_class'].value_counts()

plt.figure()
plt.bar(class_counts.index, class_counts.values)
plt.xlabel("Kelas Penyewaan")
plt.ylabel("Jumlah Data")
plt.title("Distribusi Kelas Target")
plt.show()

# @title Visualisasi Hubungan Temperature & Target
plt.figure()
plt.boxplot(
    [df[df['cnt_class']=='rendah']['temp'],
     df[df['cnt_class']=='sedang']['temp'],
     df[df['cnt_class']=='tinggi']['temp']],
    labels=['rendah','sedang','tinggi']
)
plt.xlabel("Kelas")
plt.ylabel("Temperature")
plt.title("Temperature terhadap Kelas Penyewaan")
plt.show()

corr = df.drop(columns=['cnt_class']).corr()

plt.figure()
plt.imshow(corr)
plt.colorbar()
plt.xticks(range(len(corr.columns)), corr.columns, rotation=90)
plt.yticks(range(len(corr.columns)), corr.columns)
plt.title("Korelasi Antar Fitur Numerik")
plt.show()

"""## Explanatory Analysis
1. Grafik distribusi kelas target yang saya tunjukkan adalah bahwa jumlah data pada kelas rendah, sedang, dan tinggi hampir sama. Pemahaman saya adalah bahwa dataset tidak mengalami masalah ketidakseimbangan kelas (class imbalance). Kondisi ini menguntungkan dalam proses pemodelan karena model tidak akan bias terhadap salah satu kelas tertentu.

2. Grafik boxplot saya tunjukkan bahwa adanya perbedaan distribusi temperatur pada setiap kelas penyewaan. Kelas penyewaan rendah memiliki median temperatur yang lebih rendah dibandingkan kelas sedang dan tinggi. Sementara itu, kelas penyewaan tinggi cenderung terjadi pada temperatur yang lebih tinggi. Hal ini mengindikasikan bahwa temperatur memiliki hubungan dengan tingkat penyewaan, di mana suhu yang lebih hangat cenderung meningkatkan jumlah penyewaan.

3. Dari exploratory data analysis ini terlihat bahwa sebagian besar fitur numerik tidak saling berkorelasi kuat, artinya masing-masing membawa informasi yang berbeda. Korelasi paling menonjol ada pada temp dan atemp yang sangat tinggi karena keduanya sama-sama merepresentasikan suhu, serta season dan mnth yang menunjukkan pola musiman. Selain itu, holiday dan workingday berkorelasi negatif seperti yang diharapkan, sementara windspeed cenderung berdiri sendiri karena korelasinya lemah dengan fitur lain.

"""